In [4]:
data = [1, 2, 3, 4]
result = []

for i in data:
    result.append(i)

print(result)

[1, 2, 3, 4]


In [3]:
import numpy as np 

arr = np.array([1,2,3,4])
arr10 = arr * 10

print(type(arr10))
print(arr10)

<class 'numpy.ndarray'>
[10 20 30 40]


In [8]:
data = [
    [10, 20, 30, 40], #  첫 번째 행
    [100, 200, 300, 400] #  두 번째 행 
]

print(data[0])

[10, 20, 30, 40]


In [10]:
import numpy as np
data = [
    [10, 20, 30, 40], #  첫 번째 행
    [100, 200, 300, 400] #  두 번째 행 
]

arr = np.array(data)

print(arr)

[[ 10  20  30  40]
 [100 200 300 400]]


In [17]:
print(arr[0])
print(arr[1])

10
[100 200 300 400]


In [18]:
print(arr[0,0])
print(arr[1,0])
print(arr[0][0])
print(arr[1][0])


10
100
10
100


In [16]:
print(arr[:,0])

[ 10 100]
