In [1]:
# 백터와 행렬

## vector
크기와 방향을 가진 수의 집합
벡터를 이루는 숫자 성분을 스칼라라고 하며, 열벡터와 행백터로 나뉜다.
선형대수(linalg)에서 기본적으로 열 벡터로 표현한다.
크기가 1인 벡터를 단위벡터, 모든 원소가 0인 벡터를 영벡터라고 한다.
벡터를 구분하기 위해서 대괄호를 사용 
array함수를 사용해서 생성한 1차원 배열로 벡터를 나타낸다.


좌표평면 (0,0) => 원점
x가 3, y가 2일때 벡터는 [3,2]로 표현하고 
0,0에서 3,2 까지가 크기이다. 

시점 : 벡터의 시작점
종점 : 벡터의 종료점

시점을 원점으로 옮겼을 때 크기와 방향만 같다면 같다

→
a

 
열 벡터
[
    [3],
    [2],
    [5]
]

행 벡터??
[ [3,2,5] ]
 



## 행렬
크기만 가진 행과 열로 구성된 수의 집합 
array함수를 사용해서 생성한 2차원 배열로 행렬을 나타낸다.
인덱스는 0부터 시작 
행렬 표기는 대괄호를 사용하여 나열한다.

정사각행렬: n x n 
```
1 2
3 4

1 2 3
4 5 6
7 8 9 
```

대각행렬 : 대각선을 제외한 모든 원소가 0 

```
1 0 0
0 5 0
0 0 9
```


단위행렬(항등행렬) : 대각선의 원소가 1인 행렬 
```
1 0 0
0 1 0
0 0 1
```

삼각행렬 : 주 대각선의 기준으로 위 또는 아래의 모든 원소가 0인 행렬 



In [4]:
import numpy as np
cvt = np.arange(10)
print(cvt)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
## 열벡터 생성 
cvt.shape = (len(cvt), 1)
print(cvt.shape)
print(cvt)

(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [6]:
cvt.resize(len(cvt), 1)
print(cvt.shape)
print(cvt)

(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [9]:
#  행벡터
cvt.shape = (1, len(cvt))
print(cvt.shape)
print(cvt)
print(cvt.ndim)

(1, 10)
[[0 1 2 3 4 5 6 7 8 9]]
2


In [ ]:
## linespace함수 이용 

In [13]:
## 1 ~ 10 사이의 수를 10개 추출(종료값을 포함하지 않도록)
np.linspace(1, 10, 10, endpoint=False) #  시작, 종료, 갯수, 마지막 포함여부

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [15]:
np.linspace(1, 10, 10, endpoint=True) #  시작, 종료, 갯수, 마지막 포함여부

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
## 1 ~ 10 사이의 수를 9개 추출, 종료값을 포함시키며, 샘플 간격 출력 
np.linspace(1, 10, 9, endpoint=True, retstep=True)

(array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
        10.   ]),
 1.125)

## 행렬 정의 

In [ ]:
행렬의 크기 : 행 x 열    
숫자를 직사각형 모양으로 배열해 놓은 것
행렬을 구성하는 숫자를 원소라고 함

행벡터 : 하나의 행으로 구성된 행렬   
열벡터 : 하나의 열로 구성된 행렬   


In [ ]:
# 2 x 3 행렬

In [25]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
## 벡터의 연산
### 벡터의 크기

->
r  =  √x1^2 + x2^2 + ... 
np.sqrt(np.pow(r[0], 2) + np.pow(r[1], 2) + ...)


벡터의 절대값이 벡터의 크기이다 

벡터의 크기를 계산 = 벡터의 제곱 합에 제곱근 

In [29]:
r = np.arange(5, 0, -1)
print(r)

[5 4 3 2 1]


### 손으로 계산하기

1. 각 요소의 제곱의 값을 더해서
5^2 + 4^2 + 3^2 + 2^2 + 1^2
25 + 16 + 9 + 4 + 1
55

2. 제곱근을 구한다.

In [46]:
np.sqrt(55)

7.416198487095663

In [ ]:
### 넘파이 함수 사용해서 계산하기 

In [35]:
vector_size = np.sqrt(np.power(r[0], 2) + np.power(r[1], 2) + np.power(r[2], 2) + np.power(r[3], 2) + np.power(r[4], 2))
print("스칼라 :", vector_size)

스칼라 : 7.416198487095663


In [ ]:
### 선형대수함수로 계산하기 

In [39]:
np.linalg.norm(r)

7.416198487095663

벡터의 크기를 계산 = 벡터의 곱에 제곱근 
cross 연산 : r x r 외적
dot연산 : r · r 내적.. 대응대는 요소끼리 곱 

In [52]:
np.dot(r, r)

55

r = 5 4 3 2 1 
    x x x x x 
r = 5 4 3 2 1 

dot결과는 55

In [56]:
## 최종 벡터 크기 결과 

In [58]:
np.sqrt(np.dot(r, r))

7.416198487095663

In [62]:
a = np.array([1,2])
b = np.array([5,6])

print(a + b)
print(np.add(a, b))



[6 8]
[6 8]


In [64]:
print(a - b)
print(np.subtract(a, b))

[-4 -4]
[-4 -4]


In [66]:
print(a * b)
print(np.multiply(a, b))

[ 5 12]
[ 5 12]


a [1, 2]
b [5, 6]
a * b 
1x5 2x6
a dot b = 5 + 12 (scalar)

In [ ]:
## 벡터의 내적 
벡터의 내적은 dot함수 또는 @연산자를 이용할 수 있다

In [72]:
np.dot(a, b)

17

In [74]:
a@b

17

## 벡터의 외적 
외적의 결과는 벡터이다 
a x b = np.cross(a, b)

In [76]:
np.cross(a, b)

array(-4)

In [ ]:
(1 x 6) - ( 2 x 5 ) = -4 

## 행렬의 연산 
벡터 연산과 동일하다

행렬 곱셈의 법칙 
1. 교환법칙이 성립하지 않는다.

A (3*2)
0 0
0 0
0 0

B (2*2)
0 0
0 0

첫번째 행렬의 열의 값과 두번째 행렬의 행의 값이 같아야 연산이 가능하다.
=> A(3*2) * B(2*2) 연산 가능   
=> B(2*2) * A(3*2) 연산 불가능
A * B != B * A 

2. 결합법칙은 성립한다
(A*B)*C = A*(B*C)
A(3*2) * B(2*4) => 3 * 4의 행렬

분배법칙이 성립한다.
(A+B)*C = A*C + B*C




## 전치행렬
원소들의 행 인덱스와 열 인덱스를 바꾸는 작업 

A(2*3) * B(2*3)이라고할 때 
B를 전치를 시켜 
3*2 2*3으로 만들어준다 


## 항등행렬(Identity matrix)
단위행렬(unit matrix)이라고도 하며 

3*3 행렬에서 

0 0 0 
0 0 0
0 0 0

대각선이 1인 행렬

1 0 0 
0 1 0
0 0 1

특정 행렬과 곱하면 특정행렬을 그대로 출력해주는 행렬 


In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 역행렬(Inverse matrix)

특정 행렬과 곱하면 항등행렬(I)이 결과로 나온다.   

C * A = I or A * C = I

C는 A의 역행렬 

A * A<sup>-1</sup> = I

A   
a b   
c d   

A<sup>-1</sup>    
d -b     
-c a    

1 / ad - bc

정사각 행렬일 경우에만 가능하다

In [111]:
A = np.array([[1,2],[4,5]])
invA = np.linalg.inv(A)

In [113]:
np.dot(A, invA) ## 단위행렬이 나온다 

array([[1., 0.],
       [0., 1.]])

## 행렬과 벡터의 곱셈

In [149]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]]) #  3 * 3
x = np.array([10,20,30]) #  1 * 3

In [145]:
print(A)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[10 20 30]


In [147]:
np.dot(A, x)

array([140, 320, 500])

In [137]:

# 1 2 3  10 20 30
# 4 6 7  
# 7 8 9 

print((1 * 10) + (2 * 20) + (3 * 30))
print((4 * 10) + (5 * 20) + (6 * 30))
print((7 * 10) + (8 * 20) + (9 * 30))  


140
320
500


In [159]:
v1 = A[:,0] #  1, 4, 7 : 첫 번째 행  
v2 = A[:,1] #  2, 5, 8
v3 = A[:,2] #  3, 6, 0
print(v1)
np.dot(x[0], v1) + np.dot(x[1], v2) + np.dot(x[2], v3)

[1 4 7]


array([140, 320, 500])

크기가 다른 행렬 간의 곱

m x n, n x p일때 n의 값이 같아야한다    
=> m x p 의 형태로 출력된다   



In [161]:
A = np.array([[1,2,3], [4,5,6]]) #  2 * 3
B = np.array([[1,2],[3,4,],[5,6]]) #  3 * 2 => 2 * 2 형태로 

print(A)
print(B)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [163]:
np.dot(A, B)

array([[22, 28],
       [49, 64]])

1 2 3   1 2 
4 5 6   3 4
        5 6

[1 2 3][1 3 5] = 1 + 6 + 15 => 22
[4 5 6][1 3 5] = 4 + 15 + 30 => 49

[1 2 3][2 4 6] = 2 + 8 + 18 => 28
[4 5 6][2 4 6] = 8 + 20 + 36 => 64


In [ ]:
## 스칼라와 벡터의 곱 

In [173]:
#  3행 1열 벡터
v = np.array([[1], [2], [3]]) # 열이 하나 : 열벡터 
a = 10
print(v*a)

[[10]
 [20]
 [30]]


In [171]:
np.dot(v, a)

array([[10],
       [20],
       [30]])

## 선형연립방정식 

a<sub>1</sub>x<sub>1</sub> + a<sub>2</sub>x<sub>2</sub> + a<sub>3</sub>x<sub>3</sub> = b   
a<sub>1</sub>x<sub>1</sub> + a<sub>2</sub>x<sub>2</sub> + a<sub>3</sub>x<sub>3</sub> = b   
a<sub>1</sub>x<sub>1</sub> + a<sub>2</sub>x<sub>2</sub> + a<sub>3</sub>x<sub>3</sub> = b   



전치가 필요 
```
[a1, a2, a3] [x1, x2, x3]
```
```
[a1, a2, a3] [x1,
              x2,
              x3]
```






ax = b
해를 구하기위해 역행렬을 곱한다 

a-1ax = ba-1
x = ba-1

4·x1 + 3·x2 = 23
3·x1 + 2·x2 = 16

In [214]:
A = np.array([[4,3], [3,2]])
b = np.array([23, 16])
invA = np.linalg.inv(A)
x = np.dot(b, invA)
print(x)

# A x A-1 = I 항등, 단위행렬 



[2. 5.]


## solve
solve함수를 이용하면 해를 바로 구할 수 있다.

In [212]:
x = np.linalg.solve(A, b)
print(x)

[2. 5.]


In [ ]:
1 x1 + 4 x2 + 3 x3 = 23
1 x1 + 3 x2 + 2 x3 = 16

방정식 2개, 미지수 3개 => lstsq를 사용한다 

In [ ]:
linalg.solve와 linalg.lstsq 함수는 연립방정식의 해를 구한다.
차이점은 

linalg.solve : 미지수 개수와 방정식의 개수가 같을 때 사용
linalg.lstsq : 미지수 개수와 방정식의 개수가 다를 때 사용

In [ ]:
# x = np.linalg.solve(A, b) #  미지수 개수와, 방정식의 개수가 다르기때문에 오류 출력

In [224]:
A1 = np.array([
    [1 ,4, 3],
    [1, 3, 2]
])

b1 = np.array([23, 16])

x1, residuals, rank, s = np.linalg.lstsq(A1, b1, rcond=None)
print("Solution:", x1)
print("Residuals:", residuals)
print("Rank:", rank)
print("Singular values:", s)


Solution: [-1.  3.  4.]
Residuals: []
Rank: 2
Singular values: [6.3186121  0.27411887]
