In [1]:
import numpy as np

In [2]:
b = np.array([i for i in range(1, 10)])
print(b)

[1 2 3 4 5 6 7 8 9]


In [3]:
b.resize(3,3)
print(b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [4]:
## 2차원 전치행렬

In [5]:
```
[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
```



SyntaxError: invalid syntax (452365514.py, line 1)

In [ ]:
b = b.T
print(b)

In [ ]:
print(b)

In [23]:
arr = np.array([
    
    [
        [1, 2], 
        [3, 4]
    ],
    
    [
        [5, 6],
        [7, 8]
    ]
])
print(arr.shape)
print(arr, end='\n======\n')
print(arr.T, end='\n======\n')

#print(arr.swapaxes(0, 1), end='\n======\n')


(2, 2, 2)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]


In [25]:
arr = np.array([
    
    [
        [1, 2], [3, 4]
    ],
    
    [
        [5, 6], [7, 8]
    ],
    [
        [9, 10], [11, 12]
    ]
])
print(arr.shape) #  depth:3, row:2, column:2



(3, 2, 2)


In [13]:
print(arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [14]:
print(arr.T)

[[[ 1  5  9]
  [ 3  7 11]]

 [[ 2  6 10]
  [ 4  8 12]]]


In [19]:
print(arr.T.shape)

(2, 2, 3)


In [ ]:

depth:3, row:2, column:2



[
    
    [
        [1, 2], # row 1 / columns 2
        [3, 4]  # row 2 / columns 2
    ], # depth 1
    
    [
        [5, 6], 
        [7, 8]
    ], # depth 2

    [
        [9, 10], 
        [11, 12]
    ] # depth 3
]

뎁스(면)은 3개로 구성하고 
면 안에 행은 2개이며 
그 행의 컬럼은 2개이다 



depth:2, row:2, column:3

[

    [
        [1, 5, 9], # row 1 / column  3
        [3, 7, 11], # row 2 / column 3
    ], # depth 1

    [
        [2, 6, 10], # row 1 / column  3
        [4, 8, 12], # row 2 / column  3
    ] # depth 2

]

뎁스(면)는 2개로 나누고 
각 면의 행은 2개인데 
컬럼은 3개다



1. 열은 3개이다 
[0, 0, 0]

2. 행은 2개이다 
[0, 0, 0],
[0, 0, 0]

3. 면은 2개이다 

[

    [1, 0, 0],
    [3, 0, 0]

],

[

    [2, 0, 0],
    [4, 0, 0]

],




1~12를 1차원으로 보고 

1면 1행 1열에 1
2면 1행 1열에 2

1면 2행 1열에 3
2면 2행 2열에 4 

1면 1행 2열에 5
...