# numpy
수치해석용 파이썬 라이브러리
ndarray를 이용한 다차원 행렬 자료구조 제공
파이썬 보다 빠른 연산속도
행렬 인덱싱으로 짧고 간결한 코드 
다차원 배열, 행렬 연산 가능
파이썬 기반 과학 및 수학 연산 패키지에 활용

## 1차원 배열

## numpy 배열 구조
같은 유형의 데이터만 저장
원소 개수 변경 불가
array 클래스 이용하여 생성
ndarray(다차원배열)타입
배열의 차원을 axis(축)이라고 하며, 축의 개수를 rank 라고 함 

In [4]:
import numpy as np

In [6]:
a = [1, 2, 3, 4, 5]
print(type(a))
print(a)

list

In [10]:
arr = np.array(a)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [17]:
arr2 = np.array([1, 2, 3, 'hi'])
print(arr2)
print(type(arr2[0]))

['1' '2' '3' 'hi']
<class 'numpy.str_'>


같은 유형의 데이터만 저장 가능하기 때문에 모두 str로 변경된다

In [21]:
arr2.dtype

dtype('<U11')

In [ ]:
## 차원

In [29]:
arr.ndim

1

In [27]:
np.ndim(arr)

1

In [31]:
arr.shape

(5,)

In [33]:
arr.size

5

In [43]:
arr1 = np.array([1,2,3,4])
print(arr1.shape)
print(arr1.ndim)

(4,)
1


In [45]:



arr2 = np.array([[1,2,3,4]])
print(arr2.shape)
print(arr2.ndim)

(1, 4)
2


In [ ]:
## numpy 배열 생성

In [ ]:
### empty

In [61]:
ar = np.empty((2,3))
print(ar.dtype)
print(ar.shape)
print(ar.ndim)
print(ar.size)
print(ar)

float64
(2, 3)
2
6
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
### ones

In [57]:
ar = np.ones((2,3))
print(ar.dtype)
print(ar.shape)
print(ar.ndim)
print(ar.size)
print(ar)

float64
(2, 3)
2
6
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
### zeros

In [63]:
ar = np.zeros((2,3))
print(ar.dtype)
print(ar.shape)
print(ar.ndim)
print(ar.size)
print(ar)

float64
(2, 3)
2
6
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
### full

In [69]:
ar = np.full((2,3), 10)
print(ar.dtype)
print(ar.shape)
print(ar.ndim)
print(ar.size)
print(ar)

int32
(2, 3)
2
6
[[10 10 10]
 [10 10 10]]


In [ ]:
### eye 

In [81]:
ar = np.eye(4)
print(ar.dtype)
print(ar.shape)
print(ar.ndim)
print(ar.size)
print(ar)

float64
(4, 4)
2
16
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
## 배열의 타입 변경 

In [113]:
arr1 = np.ones((2,2))
print(arr1.dtype)

float64


In [117]:
arr1 = arr1.astype(np.int64)
print(arr1.dtype)

int64


In [119]:
arr1 = arr1.astype(np.float32)
print(arr1.dtype)

float32


In [121]:
arr1.astype(int)
print(arr1.dtype)

float32


In [ ]:
## 배열 타입 지정

In [123]:
arr = np.array([1,2,3], dtype=np.int32)
print(arr.dtype)

int32


In [ ]:
## numpy 배열 사용

In [137]:
arr = np.full((3,3), 1)
print(arr)
print(arr.itemsize)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
4


In [139]:
arr = np.ones((3,3))
print(arr)
print(arr.itemsize)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
8


In [156]:
a = np.array([1, 2, 3, 4])
print(a.shape)

(4,)


In [158]:
a.shape = 1, 4

In [160]:
print(a.shape)

(1, 4)


In [162]:
print(a)

[[1 2 3 4]]


In [164]:
a.shape = 2,2

In [166]:
print(a.shape)

(2, 2)


In [168]:
print(a)

[[1 2]
 [3 4]]


In [170]:
a.size

4

In [172]:
b = np.array([1,2,3,4,5])
b.shape

(5,)

In [174]:
b = np.array([1,2,3,4,5])
b.shape = 1, 5
b.shape

(1, 5)

In [ ]:
## 배열 차원 변경 

In [184]:
c = np.array([[1,2,3], [3,4,5], [7,8,9]])
print(c.shape)
print(c.size)
print(c)

(3, 3)
9
[[1 2 3]
 [3 4 5]
 [7 8 9]]


In [188]:
c.shape = c.size
print(c.shape)
print(c)

(9,)
[1 2 3 3 4 5 7 8 9]


In [ ]:
### resize

In [198]:
a = np.array([1,2,3,4,5,6])
print(a.shape)

(6,)


In [200]:
a.resize(2,3)
print(a.shape)

(2, 3)


In [202]:
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
### reshape

In [208]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
## 배열 데이터 공유

In [254]:
a = np.array([1,2,3,4,5,6])
a.view()

array([1, 2, 3, 4, 5, 6])

In [256]:
b = a.view()
print(b)

[1 2 3 4 5 6]


In [258]:
a is b

False

In [260]:
b.base

array([1, 2, 3, 4, 5, 6])

In [262]:
a is b.base

True

In [264]:
b[0] = 10
print(b)

[10  2  3  4  5  6]


In [266]:
print(a)

[10  2  3  4  5  6]


In [274]:
d = a.reshape(2,3)
print(d)
print(a)

[[10  2  3]
 [ 4  5  6]]
[10  2  3  4  5  6]


In [280]:
a = np.array([1,2,3,4,5,6])
d = a.reshape(2,3)
print(d)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [282]:
a[-1] = 100
print(a)
print(d)

[  1   2   3   4   5 100]
[[  1   2   3]
 [  4   5 100]]


## 스칼라
길이가 1인 벡터(차원을 갖지 않는 배열)
숫자값 하나
단일차원의 값 ex) 1, 2, 3, ...
크기만 있고 방향을 가지지 않은 양
좌표평면 위의 점(1, 3)은 2차원이기때문에 스칼라가 아니다.

In [290]:
data = np.array([45])
print(type(data))
print(data.shape)
print(data.ndim)

<class 'numpy.ndarray'>
(1,)
1


In [292]:
data = np.array(45)
print(type(data))
print(data.shape)
print(data.ndim)

<class 'numpy.ndarray'>
()
0


In [ ]:
### 스칼라의 타입 자료형 
1. int
2. float
3. none
4. bool

In [294]:
int(3.14)

3

In [296]:
int('100')

100

In [298]:
int('3.7')

ValueError: invalid literal for int() with base 10: '3.7'

In [304]:
int('100', 16) ## 진수

256

In [306]:
float(10)

10.0

In [312]:
float('3.14')

3.14

In [318]:
data = None
print(data)

None


In [320]:
bool(0)

False

In [326]:
bool(2)

True

In [328]:
bool('')

False

In [330]:
bool('bool?')

True

In [336]:
bool([])

False

In [338]:
bool([1])

True

## 배열과 스칼라의 연산 

In [26]:
import numpy as np
a = np.array([1,2,3])
a + 1

array([2, 3, 4])

In [28]:
b = np.array([10,10,10])
b + a

array([11, 12, 13])

In [30]:
c = np.array([1,1,1,1])
a + c

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

shape이 달라서 연산이 불가능하다.

In [34]:
a + 0.14

array([1.14, 2.14, 3.14])

In [ ]:
## 인덱싱과 슬라이싱

슬라이싱의 결과는 ndarray이며 원본 배열의 view이다(원본도 같이 바뀜)

In [106]:
a = np.arange(0, 8, 1)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [108]:
b = np.arange(8)
print(b)
print(type(b))

[0 1 2 3 4 5 6 7]
<class 'numpy.ndarray'>


In [110]:
c = np.arange(8, 2, -1)
c

array([8, 7, 6, 5, 4, 3])

In [120]:
a.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [122]:
a

array([0, 1, 2, 3, 4, 5, 6, 7])

In [124]:
a.resize(2,4)

In [126]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [130]:
a[1][0]

4

In [ ]:
## 전치행렬

In [144]:
a.resize(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [146]:
a.T

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

n행 m열이 m행 n열로 변경된다 

In [148]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [152]:
a.resize(2,2,2)
a

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [154]:
a.T

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [156]:
a.swapaxes(0, 1)

array([[[0, 1],
        [4, 5]],

       [[2, 3],
        [6, 7]]])