In [1]:
# 백터와 행렬

## vector
크기와 방향을 가진 수의 집합
벡터를 이루는 숫자 성분을 스칼라라고 하며, 열벡터와 행백터로 나뉜다.
선형대수(linalg)에서 기본적으로 열 벡터로 표현한다.
크기가 1인 벡터를 단위벡터, 모든 원소가 0인 벡터를 영벡터라고 한다.
벡터를 구분하기 위해서 대괄호를 사용 
array함수를 사용해서 생성한 1차원 배열로 벡터를 나타낸다.


좌표평면 (0,0) => 원점
x가 3, y가 2일때 벡터는 [3,2]로 표현하고 
0,0에서 3,2 까지가 크기이다. 

시점 : 벡터의 시작점
종점 : 벡터의 종료점

시점을 원점으로 옮겼을 때 크기와 방향만 같다면 같다

→
a

 
열 벡터
[
    [3],
    [2],
    [5]
]

행 벡터??
[ [3,2,5] ]
 



## 행렬
크기만 가진 행과 열로 구성된 수의 집합 
array함수를 사용해서 생성한 2차원 배열로 행렬을 나타낸다.
인덱스는 0부터 시작 
행렬 표기는 대괄호를 사용하여 나열한다.

정사각행렬: n x n 
```
1 2
3 4

1 2 3
4 5 6
7 8 9 
```

대각행렬 : 대각선을 제외한 모든 원소가 0 

```
1 0 0
0 5 0
0 0 9
```


단위행렬(항등행렬) : 대각선의 원소가 1인 행렬 
```
1 0 0
0 1 0
0 0 1
```

삼각행렬 : 주 대각선의 기준으로 위 또는 아래의 모든 원소가 0인 행렬 



In [4]:
import numpy as np
cvt = np.arange(10)
print(cvt)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
## 열벡터 생성 
cvt.shape = (len(cvt), 1)
print(cvt.shape)
print(cvt)

(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [6]:
cvt.resize(len(cvt), 1)
print(cvt.shape)
print(cvt)

(10, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [9]:
#  행벡터
cvt.shape = (1, len(cvt))
print(cvt.shape)
print(cvt)
print(cvt.ndim)

(1, 10)
[[0 1 2 3 4 5 6 7 8 9]]
2


In [ ]:
## linespace함수 이용 

In [13]:
## 1 ~ 10 사이의 수를 10개 추출(종료값을 포함하지 않도록)
np.linspace(1, 10, 10, endpoint=False) #  시작, 종료, 갯수, 마지막 포함여부

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [15]:
np.linspace(1, 10, 10, endpoint=True) #  시작, 종료, 갯수, 마지막 포함여부

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [17]:
## 1 ~ 10 사이의 수를 9개 추출, 종료값을 포함시키며, 샘플 간격 출력 
np.linspace(1, 10, 9, endpoint=True, retstep=True)

(array([ 1.   ,  2.125,  3.25 ,  4.375,  5.5  ,  6.625,  7.75 ,  8.875,
        10.   ]),
 1.125)

## 행렬 정의 